name: Gradle Develocity injection

inputs:
  project-root-directory:
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
  - name: Inject Develocity for Gradle
    shell: bash
    run: |
      mkdir -p ~/.gradle/init.d
      cp -n ${{ github.action_path }}/resources/develocity-injection.init.gradle ~/.gradle/init.d/develocity-injection.init.gradle

      echo "DEVELOCITY_INJECTION_ENABLED=true" >> "$GITHUB_ENV"
      echo "DEVELOCITY_INJECTION_INIT_SCRIPT_NAME=develocity-injection.init.gradle" >> "$GITHUB_ENV"
      echo "DEVELOCITY_URL=https://ge.solutions-team.gradle.com" >> "$GITHUB_ENV"
      echo "DEVELOCITY_PLUGIN_VERSION=3.17" >> "$GITHUB_ENV"
