name: Maven Develocity injection

inputs:
  project-root-directory:
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
  - name: Inject Develocity for Maven
    shell: bash
    working-directory: ${{ inputs.project-root-directory }}
    run: |
      mkdir -p .mvn
      cp -n ${{ github.action_path }}/resources/.mvn/extensions.xml .mvn/extensions.xml
      cp -n ${{ github.action_path }}/resources/.mvn/develocity.xml .mvn/develocity.xml
