name: Maven Develocity injection

inputs:
  project-root-directory:
    required: false
    default: ${{ github.workspace }}
  develocity-access-key:
    required: true
runs:
  using: "composite"
  steps:
  - name: Inject Develocity for Maven
    shell: bash
    working-directory: ${{ inputs.project-root-directory }}
    run: |
      mkdir -p .mvn
      cp -n ${{ github.action_path }}/resources/extensions.xml .mvn/extensions.xml
      cp -n ${{ github.action_path }}/resources/develocity.xml .mvn/develocity.xml
      cp -n ${{ github.action_path }}/resources/develocity-custom-user-data.groovy .mvn/develocity-custom-user-data.groovy

      echo "DEVELOCITY_URL=https://ge.solutions-team.gradle.com" >> "$GITHUB_ENV"
      echo "DEVELOCITY_ACCESS_KEY=${{ inputs.develocity-access-key }}" >> "$GITHUB_ENV"
